repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.244
  hooks:
    - id: ruff
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
    - id: isort
      args: ["--check"]
