#!/bin/bash -e
# ./docker-build <tag>
# docker run -it -p 80:80 reece/anyvar
# curl http://localhost/info

imagename=reece/anyvar

eq="============================================================================"
e () { echo "$eq"; echo "+ $@"; $@; }


tag="${1:-master}"
shift

e hg up "$tag"

e docker build -t $imagename:$tag "$@" .
e docker tag $imagename:$tag $imagename:latest 
e docker push $imagename:$tag
e docker push $imagename:latest 

