#!/bin/bash -e

imagename=reece/anyvar

eq="============================================================================"
e () { echo "$eq"; echo "+ $@"; $@; }

tag=$(git describe --tags)

e docker build -t $imagename:$tag "$@" .
e docker push $imagename:$tag

e docker tag $imagename:$tag $imagename:latest 
e docker push $imagename:latest 
