version: "4"

services:
  uta:
    build: ./docker/uta/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # TODO real auth method
    volumes:
      - ./docker/data-uta:/var/lib/postgresql/data
  dynamodb:
    build: ./docker/dynamodb/
    user: root
    expose:
      - 8001
  normalizer:
    depends_on:
      - postgres
      - dynamodb
    volumes:
      - ./docker/data-normalizer:/app/mounted-data
    build: ./docker/variation-normalizer/
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    environment:
      UTA_DB_URL: postgres://uta_admin@uta:5432/uta/uta_20210129
      GENE_NORM_DB_URL: http://dynamodb:8001
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: anyvar
      POSTGRES_HOST_AUTH_METHOD: trust  # TODO real auth method
    volumes:
      - ./docker/data-anyvar:/var/lib/postgresql/data
  app:
    depends_on:
      - normalizer
      - postgres
    build: .
    ports:
      - 5000:5000
    environment:
      ANYVAR_STORAGE_URI: postgresql://postgres@postgres:5432/anyvar
      ANYVAR_VARIATION_NORMALIZER_URI: http://normalizer:8000/variation/
