# TODO: Migrate to private container network. (This config currently
# uses host networking, which is fragile in the context of services
# that compete with any ports used herein.)

version: "3"

services:
  anyvar:
    image: reece/anyvar:latest
    expose:
      - 5001
    ports:
      - 5001:5000
    volumes:
      - seqrepo_vol:/usr/local/share/seqrepo
    depends_on:
      - redis
      - seqrepo-rest-service
    #  - uta
    #environment:
    #  # UTA_DB_URL:
    #  # SEQREPO_REST_SERVICE_URL:

  redis:
    expose:
      - 6379
    image: redis:latest
    volumes:
      - anyvar_redis_vol:/data

  seqrepo-rest-service:
    # Test: curl http://localhost:5000/seqrepo/1/sequence/refseq:NM_000551.3
    expose:
      - 5000
    ports:
      - 5000:5000
    image: biocommons/seqrepo-rest-service:latest
    volumes:
      - seqrepo_vol:/usr/local/share/seqrepo

  # uta:
  #   # Test:
  #   # psql -XAt postgres://anonymous@localhost/uta -c 'select count(*) from transcript'
  #   # 249909
  #   image: biocommons/uta:uta_20180821
  #   volumes:
  #     - uta_vol:/var/lib/postgresql/data


volumes:
  seqrepo_vol:
    external: true
  uta_vol:
    external: true
  anyvar_redis_vol:
