version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "%(threadName)s %(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: "anyvar.log"
    mode: "a"

root:
  level: INFO
  handlers: [console, file]
  propagate: yes

loggers:
  anyvar.restapi.main:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  anyvar.storage.sql_storage:
    level: DEBUG
    handlers: [console, file]
    propagate: no
