name: Requirement
description: Add a new requirement to the project
body:
  - type: textarea
    attributes:
      label: Description
      description: Provide a concise high-level overview of the requirement.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      description: How important is this?
      multiple: false
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: |
        This is the source of truth for this requirement—if it's not defined here, it is not in scope. Include scenarios that cover expected behavior as well as edge cases.
        Example: "Given a valid VCF file containing one or more variants, when the user uploads the file to the `/vcf` endpoint, then AnyVar registers each variant contained in the VCF"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Out of Scope
      description: Is there anything we DON'T want in this requirement? Document that here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Open Questions
      description: |
        Are there questions that need to be resolved before this requirement can be implemented? List them here.
        ⚠️ Note: Once questions have been resolved, remove them and add relevant info to the Acceptance Criteria and Changelog.
      required: false
  - type: textarea
    attributes:
      label: Changelog
      description: |
        If this requirement has changed over time, document what changed and why. ⚠️ Remember to update Acceptance Criteria accordingly!
        Example: "04/29/26 - Decided NOT to save original input expression (e.g., HGVS expression, etc.) during variant registration to encourage VRS usage"
      required: false
