"""Initial schema

Revision ID: 18469f31ca97
Revises:
Create Date: 2026-07-29 13:21:44.275633

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18469f31ca97"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extensions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sequence_references",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "molecule_type",
            sa.Enum("genomic", "RNA", "mRNA", "protein", name="molecule_type"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variation_mappings",
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("dest_id", sa.String(), nullable=False),
        sa.Column(
            "mapping_type",
            sa.Enum(
                "LIFTOVER_TO",
                "TRANSCRIBE_TO",
                "TRANSLATE_TO",
                name="mapping_type",
                metadata=sa.MetaData(),
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source_id", "dest_id", "mapping_type"),
    )
    op.create_table(
        "vrs_objects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "vrs_object",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("sequence_reference_id", sa.String(), nullable=False),
        sa.Column("start_pos", sa.Integer(), nullable=True),
        sa.Column("end_pos", sa.Integer(), nullable=True),
        sa.Column("start_outer", sa.Integer(), nullable=True),
        sa.Column("start_inner", sa.Integer(), nullable=True),
        sa.Column("end_outer", sa.Integer(), nullable=True),
        sa.Column("end_inner", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sequence_reference_id"],
            ["sequence_references.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alleles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("location_id", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "canonical_alleles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("allele_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allele_id"],
            ["alleles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "protein_sequence_consequences",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("allele_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["allele_id"],
            ["alleles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("protein_sequence_consequences")
    op.drop_table("canonical_alleles")
    op.drop_table("alleles")
    op.drop_table("locations")
    op.drop_table("vrs_objects")
    op.drop_table("variation_mappings")
    op.drop_table("sequence_references")
    op.drop_table("extensions")
    # ### end Alembic commands ###
