DROP DATABASE IF EXISTS anyvar;
DROP USER IF EXISTS anyvar;

CREATE USER anyvar WITH PASSWORD 'anyvar-pw';
CREATE DATABASE anyvar;
GRANT ALL PRIVILEGES ON DATABASE anyvar TO anyvar;

\c anyvar
GRANT ALL PRIVILEGES ON SCHEMA public TO anyvar;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO anyvar;
