name: checks
on: [push, pull_request]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      seqrepo:
        image: biocommons/seqrepo-rest-service:0.2.2
        ports:
          - 5000:5000
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: anyvar_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up AnyVar
        run: python3 -m pip install '.[test]'
      - name: Run tests
        env:
          ANYVAR_TEST_STORAGE_URI: "postgresql://postgres:postgres@localhost:5432/anyvar_test"
        run: python3 -m pytest
